### PR TITLE
Argument "args" on scaffoldContractRead

### PR DESCRIPTION
**Pull request by carletex**
This is kind of a hotfix (until #147 #207 or #200 is merged). That's why I went with `any[]` :D 

On yesterday's hacking session, we realized we couldn't read contract data that require params.

e.g.

```
  const { data } = useScaffoldContractRead("YourContract", "userGreetingCounter", [
    "0xWHATEVER_ADDRESS",
  ]);
```

Technically you could pass it on `readConfig`, but I think this is more clear. Should we also add `writeConfig` on `scaffoldContractWrite`? (we can leave it for other PR)

### CODE REVIEW

**Comment by rin-st** [comment]
Have you tried 
```
const { data } = useScaffoldContractRead("YourContract", "userGreetingCounter", {
    args: ["0xWHATEVER_ADDRESS"]
});
```
?

**Comment by carletex** [comment]
@rin-st Yep, that worked. See my PR comment:

> Technically you could pass it on readConfig, but I think this is more clear.

I was trying to be more explicit (and using the same signature as in useScaffoldContractWrite).

But if we think using the `readConfig` to override the call is clear enough, happy to close this!

**Comment by technophile-04** [comment]
> Technically you could pass it on readConfig, but I think this is more clear. Should we also add writeConfig on scaffoldContractWrite? (we can leave it for other PR)

Lol yup love this pattern makes more intutive, +1 for `write` too !

**Comment by rin-st** [comment]
> Yep, that worked. See my PR comment:

oops, sorry :)

I think if you're adding args here, you should remove it from config, so user can't add args here and in config

**Comment by carletex** [comment]
> I think if you're adding args here, you should remove it from config, so user can't add args here and in config

Not sure what you mean. `readConfig` is meant to pass our hook some extra wagmi config props (to override the ones we've set or to add props that we are not using).

I don't think people do this:
```js
const { data } = useScaffoldContractRead("YourContract", "userGreetingCounter", ["0xWHATEVER_ADDRESS"], {
    args: ["some_other_stuff??"]
});
```

And if they do.. :unamused: haha

I guess you mean to remove `args` from `readConfig`?

**Comment by rin-st** [comment]
> I guess you mean to remove args from readConfig?

yep

> And if they do.. 😒 haha

if we'll give them a possibility to do it, they'll do 😄 . Not critical, we can do it later. And they also can pass `functionName` to `readConfig` too

**Comment by carletex** [comment]
> if we'll give them a possibility to do it, they'll do smile . Not critical, we can do it later. And they also can pass functionName to readConfig too

Yep, I see your point. As you said, not critical, so merging it for now.

Thanks!

**Pull request merged**
