### PR TITLE
Basic draft for v2 of Purpose contract

### PR DESCRIPTION
**Pull request by technophile-04**
### Description
This is a basic draft for #80

### CODE REVIEW

**Comment by carletex** [comment]
Hey @technophile-04 great starting point!

I know this was still a Draft, but since I've been talking with Austin & Andrea about this, I took a look and committed some stuff.

I'm thinking in 3 things:
- Having a rich /debug page
- Using some of the most common stuff in solidity
- Having an Example UI that can play nice with the contract.

This is just a first try, ofc! Even if we merge this, I'm expecting to make a bunch of tweaks afterwards.

Can you test and see if everything works as expected? I noticed that the Balance (from the burner wallet AND the contract) is not updating.

**Comment by carletex** [comment]
@technophile-04 Made another tweak to make the contract even simpler for now.

>  I noticed that the Balance (from the burner wallet AND the contract) is not updating.

I think this was just only a matter of not showing enough ETH decimals. Fixed it!

**Comment by technophile-04** [comment]
### Description  
While testing found a bug that if you try to withdraw funds from the contract it gives "Transaction out of gas" error. 

### Steps to reproduce 
1) Make sure initially the balance of the contract is 0
2) Set purpose with some value of ETH
3) try to withdraw funds using the `withdraw` function and you will get the error.  

### Tried debugging and below is the explanation for issue
- Since we are using `usePrepareContractWrite` what it does is it sends `eth_estimateGas` call in background before hand when app renders. 
- "Transaction ran out of gas" this error only comes when initially the contract balance is 0 -> setPurpse -> withdraw, because `usePrepareContractWrite` has already made `eth_estimateGas` call for `withdraw` function. 
- Since initially the contract balance is 0 the `eth_estimateGas` returns lower value.
- Now, when you setPurpose and then try to `withdraw` because estimateGas was when contract balance was 0 and now since it has increased it fails
- If you refresh the page and then try to `withdraw` it works because now on app render since initial contract balance is > 0, the `eth_estimateGas` call returns higher value and `withdraw` transaction go through.


https://user-images.githubusercontent.com/80153681/211212928-420559ac-2bf8-4603-b4a6-bcbd9d0222b2.mov

### Approach taken 
Removed the `usePrepareContract` hook at [3740b03](https://github.com/scaffold-eth/se-2/pull/86/commits/3740b03b83c5b2e6e34f0f481154a2da0d298d5e) . 

### Reson for current approch 
- As mentioned in #59, even if we remove the `usePrepareContractWrite` hook the UX won't change because we are not using it properly and it's as good as not using it.
- found this to be a minimal and sweet solution :)

PS : If we go with the current approach, it will fix #59 too.

**Comment by carletex** [comment]
@technophile-04 this is amazing, thank you!!

From #59 
> Ideally the send button should be disabled until we input correct values. But I also wonder if this is good DX, since while developing locally we want it to be raw and check directly by sending transaction if it fails.

I 100% agree with you here.

It's always scary to use something that reads "recklesslyUnprepared" haha, but I think there is a valid reason here. This solution is working (and fixing 2 issues at the same time!) so I'd say: let's go for it. 

There might a solution that recalculate the gas estimations, but let's not worry about that now. I don't think the "UX pitfalls" wagmi docs mention affect us in the /debug page. We'd have to think if we want to take the same approach when we do #88

**Review by carletex — APPROVED** [review]

**Pull request merged**
